version: '3.8'

services:
  app:
    build: .
    command: sh -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: ${APP_CONFIG__DB__URL}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
      - ./alembic.ini:/app/alembic.ini

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${APP_CONFIG__DB__USER:-test_user}
      POSTGRES_PASSWORD: ${APP_CONFIG__DB__PASSWORD:-password}
      POSTGRES_DB: ${APP_CONFIG__DB__DB:-my_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${APP_CONFIG__DB__USER} -d $${APP_CONFIG__DB__DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
